/* ───────────────────────────────────────────────────────────
   ai-config.js — AI 画像機能の共有定義(圧縮・スタイル・モデル表)
   App.jsx から抽出(Phase 1)。React 非依存。
   ─────────────────────────────────────────────────────────── */

/* ── 圖像壓縮(上傳用) ── */
export async function fileToCompressedDataURL(file, maxW = 1080, quality = 0.78) {
  const dataURL = await new Promise((res, rej) => {
    const r = new FileReader();
    r.onload = () => res(r.result); r.onerror = rej;
    r.readAsDataURL(file);
  });
  return await new Promise((res, rej) => {
    const im = new Image();
    im.onload = () => {
      const scale = Math.min(1, maxW / im.width);
      const c = document.createElement("canvas");
      c.width = Math.round(im.width * scale);
      c.height = Math.round(im.height * scale);
      c.getContext("2d").drawImage(im, 0, 0, c.width, c.height);
      res(c.toDataURL("image/jpeg", quality));
    };
    im.onerror = rej;
    im.src = dataURL;
  });
}

/* ── AIスタイル変換(nano banana) ── */
export const AI_STYLES = [
  { id: "ukiyoe", label: "浮世絵風",
    prompt: "Completely repaint this image as a Japanese ukiyo-e woodblock print (浮世絵). You MUST restyle the SUBJECT itself, not only the background: rebuild the subject's colors as bold flat planes of ukiyo-e pigment, and redraw all of its contours and lines as strong calligraphic black woodblock linework. Apply ukiyo-e treatment everywhere — flat color fills, hand-carved outline quality, woodblock-print paper texture, decorative stylized waves and clouds, bokashi gradients, and a vivid ornamental traditional palette. Do not leave the subject looking photographic while only the background changes; the subject's color and linework must be fully reinterpreted in ukiyo-e style. Output only the image." },
  { id: "cel", label: "80年代セル画風",
    prompt: "Completely redraw this entire image — BOTH the subject AND the background — as a 1980s Japanese robot/mecha anime cel-animation frame. Fully re-render everything by hand in that era's style: rough, slightly uneven hand-drawn ink outlines, visibly hand-painted limited flat colors with hard two-tone cel shading, and the coarse texture of vintage analog animation cels. Embrace imperfection — the linework should look hand-inked and a little rough, not clean or digital. Add a moderate amount of film grain / analog noise and slight VHS-style softness throughout. Nothing should remain photographic; the whole frame must read as a hand-drawn 80s anime cel. Output only the image." },
  { id: "impressionist", label: "印象派風",
    prompt: "Completely repaint this image as a French Impressionist oil painting in the manner of Monet and Renoir. Re-render BOTH the subject AND the background entirely with loose, broken brushstrokes and small dabs of pure, unmixed color placed side by side; capture vibrant natural daylight, shimmering atmosphere, soft blurred edges and visible canvas texture, in the plein-air spirit of Impressionism. Nothing may remain photographic — every surface must read as dappled Impressionist paint. CONSTRAINTS: do NOT change the composition, camera angle, pose, proportions or framing; only the medium becomes an Impressionist painting. Output only the image." },
  { id: "shiningfinger", label: "シャイニングフィンガー風",
    prompt: "Redraw this mobile suit as a dynamic finishing-move action scene in the hand-drawn cel-animation art style of mid-1990s Japanese super-robot anime (in the visual spirit of Mobile Fighter G Gundam). Re-pose the machine performing the legendary 'Shining Finger' attack: a powerful forward lunge with the right arm thrust out and the open right hand blazing with a brilliant glowing energy aura, radiating intense heat-haze, light streaks and sparks; add explosive energy bursts, speed lines and dramatic rim lighting in the background. Use bold hand-inked outlines, flat two-tone cel shading with hard highlights, and the vivid saturated palette and analog texture of 90s mecha TV anime. You MAY change the pose, camera angle and background to depict this action dramatically, but keep it recognizably the same machine. Output only the image." },
  { id: "lineart", label: "設定線稿風",
    prompt: "Redraw this mobile suit as a SINGLE comprehensive mechanical design sheet (設定ラフ・線画) drawn entirely with REAL graphite PENCIL on off-white sketch paper: visible hand-drawn pencil strokes with varied line pressure, light construction/guide lines, faint smudging and eraser marks, and genuine pencil-on-paper texture — NOT clean digital vector lines. In ONE image, lay out together: a full-body upright front-view figure as the main reference; surrounding rough detail studies of key parts (head/face, hands, joints, backpack); a small internal-structure cutaway; and the machine's weapons/equipment as separate item sketches. Add plenty of HANDWRITTEN annotations and labels drawn in pencil (Japanese and/or English notes naming the parts, arrows pointing to details, small measurements and remarks) as on a real mechanical designer's working sheet. Monochrome graphite only. Output only the image." },
  { id: "manga", label: "漫畫風",
    prompt: "Redraw this image as a dramatic black-and-white Japanese manga panel: pure monochrome (no color), bold confident ink linework, high-contrast screentone (網点) shading and expressive manga hatching. CRITICAL: faithfully preserve the subject's EXACT pose, proportions, orientation, framing and overall composition from the original photo — do NOT change the pose, action or viewpoint; only the drawing medium becomes manga.",
    fields: [
      { key: "artist", label: "漫畫家の作風(任意)", type: "text", placeholder: "例: 大友克洋 / 鳥山明" },
      { key: "line", label: "セリフ(任意)", type: "text", placeholder: "コマ内のセリフ" },
    ],
    extra: (o) => {
      let s = "";
      if (o.artist && o.artist.trim()) s += " You MUST strongly and unmistakably emulate the highly distinctive drawing style of manga artist " + o.artist.trim() + " — their characteristic linework, inking, anatomy, screentone usage, eyes and overall art-style signature must be clearly and recognizably reproduced.";
      if (o.line && o.line.trim()) s += " Add a manga speech balloon containing this dialogue, hand-lettered naturally: 「" + o.line.trim() + "」.";
      return s + " Remember: keep the subject's original pose and composition unchanged. Output only the image.";
    } },
  { id: "cubism", label: "キュビスム風",
    prompt: "Completely repaint this image as a Cubist painting in the manner of Pablo Picasso and Georges Braque (c.1910s). You MUST fully fracture and reconstruct BOTH the subject AND the background — nothing may remain photographic. Shatter the machine into faceted, overlapping geometric planes seen simultaneously from multiple viewpoints (front, side and three-quarter angles fused into one image), flattening depth into an interlocking mosaic of angular shards. Use the restrained Cubist palette of ochres, greys, browns, muted greens and blacks, with passages of flat collaged color and stencilled letters or numbers in the Synthetic Cubist manner. Apply visible brushwork, facet shading and a shallow, ambiguous picture space. The machine must dissolve into Cubist geometry yet stay just recognizable. You MAY freely fragment and recompose the forms. Output only the image." },
  { id: "constructivism", label: "構成主義風",
    prompt: "Completely redesign this image as a 1920s Russian Constructivist / avant-garde propaganda poster in the manner of Alexander Rodchenko and El Lissitzky. You MUST rebuild the whole image — nothing photographic may remain. Reduce the machine to bold high-contrast graphic forms and place it in a dynamic, diagonal, off-kilter composition driven by strong geometric shapes, hard diagonals, circles and bars. Use a strict limited palette of red, black and off-white (with occasional grey), flat poster-like areas of color, and a high-contrast photomontage feel. Add bold Constructivist sans-serif and Cyrillic-style block lettering set on aggressive diagonals, plus simple geometric design elements. The result must read as a striking revolutionary graphic poster. You MAY crop, rotate and recompose dramatically for maximum graphic impact. Output only the image." },
  { id: "artnouveau", label: "アール・ヌーヴォー風",
    prompt: "Completely repaint this image as an Art Nouveau illustration in the decorative manner of Alphonse Mucha. You MUST restyle BOTH the subject AND its surroundings — nothing may remain photographic. Re-render the machine with flowing, elegant 'whiplash' organic outlines and flat decorative color, and surround it with an ornate Art Nouveau composition: a large circular halo or arched decorative frame behind it, swirling botanical motifs, vines, flowers and stylised flowing lines, intricate ornamental borders, and luminous gold-leaf accents. Use a soft, muted, harmonious palette of pastels, golds and jewel tones with delicate linework. The hard mechanical subject should be wrapped in graceful decorative Art Nouveau ornament like a poster icon, kept recognizable at the centre of the design. Output only the image." },
  { id: "popart", label: "ポップアート風",
    prompt: "Completely redraw this image as a 1960s Pop Art comic panel in the style of Roy Lichtenstein and Andy Warhol. You MUST fully restyle BOTH the subject AND the background — nothing photographic may remain. Re-render everything with thick bold black outlines, flat blocks of bright primary color (red, yellow, blue) and visible Ben-Day halftone dot shading. Add a comic-book feel: a dramatic flat-color or dot-pattern background, optional bold sound-effect or speech-balloon graphics, and crisp screen-print quality. Embrace the high-contrast, mass-printed look of vintage pop comics — limited punchy colors, hard edges, no soft gradients. The whole image must read as a graphic Pop Art print. Output only the image." },
  { id: "fauvism", label: "フォーヴィスム風",
    prompt: "Completely repaint this image as a Fauvist painting in the manner of Henri Matisse and André Derain. You MUST repaint BOTH the subject AND the background — nothing may remain photographic. Discard naturalistic color entirely and use wild, arbitrary, intensely saturated non-realistic hues — the machine painted in clashing reds, oranges, electric blues, greens and purples — with bold expressive brushstrokes and thick visible paint. Simplify forms into flat, vigorous patches of pure color with strong outlines, vibrant contrasting backgrounds and energetic, almost crude brushwork. Color and feeling lead over realism. CONSTRAINTS: keep the original pose, composition and framing — only the medium and color become Fauvist. Output only the image." },
  { id: "sumie", label: "水墨画風",
    prompt: "Completely repaint this image as a traditional East Asian sumi-e ink-wash painting (水墨画) on rice paper. You MUST fully restyle BOTH the subject AND the background — nothing may remain photographic. Re-render the machine entirely in monochrome black ink: fluid expressive brushstrokes, graded ink washes from deep black to pale grey, dry-brush texture and confident calligraphic lines, with much of the composition left as empty negative space (留白). Capture the subject economically with minimal, gestural brushwork rather than fine detail; suggest atmosphere with soft ink mist and bleeding wet edges on absorbent paper. Optionally add a small red seal stamp and faint paper texture. The whole image must read as an elegant, restrained ink painting. Output only the image." },
  { id: "stainedglass", label: "ステンドグラス風",
    prompt: "Completely transform this image into a Gothic cathedral stained-glass window. You MUST rebuild BOTH the subject AND the background — nothing may remain photographic. Reconstruct the entire scene out of flat, glowing panes of translucent colored glass separated by thick black lead came lines outlining every shape. Render the machine as a radiant icon assembled from jewel-toned glass — deep blues, rich reds, golds, emerald greens and amber — backlit so the colors glow with luminous light as if sunlight streams through. Add an ornate stained-glass frame or rose-window motifs, decorative geometric borders, and the subtle texture and slight irregularity of real antique glass. The machine should sit enshrined like a saint in a sacred window, kept recognizable. Output only the image." },
  { id: "moebius", label: "メビウス風",
    prompt: "Completely redraw this image as a Franco-Belgian bande dessinée science-fiction illustration in the iconic style of Mœbius (Jean Giraud). You MUST restyle BOTH the subject AND the background — nothing may remain photographic. Use clean, precise, even-weight 'ligne claire' ink outlines with fine cross-hatching, and fill with flat, subtly graded color in Mœbius's distinctive palette of warm sand, terracotta, turquoise, lilac and soft pastel skies. Place the machine within a vast, surreal sci-fi dreamscape — endless desert horizons, strange organic-mechanical structures, distant alien vistas and luminous gradient skies. Crisp, meditative, otherworldly and richly detailed in the European comics tradition. Keep the machine clearly recognizable. Output only the image." },
  { id: "amcomic", label: "アメコミ風",
    prompt: "Completely redraw this image as a modern American superhero comic-book illustration in the bold inked style of Marvel/DC comics. You MUST restyle BOTH the subject AND the background — nothing photographic may remain. Use dynamic heavy ink outlines with dramatic spotted blacks, muscular rendering, foreshortened action posing and energetic motion. Color it with bold saturated hues and modern digital comic cel-shading with hard highlights and gradient rendering. Add an explosive dynamic background with action lines, energy bursts and dramatic perspective. The whole image must read as a punchy, high-impact American comic panel. You MAY heighten the pose and camera angle for drama. Output only the image." },
  { id: "woodcut", label: "木版画風",
    prompt: "Completely transform this image into a bold black-and-white woodcut / woodblock relief print in the stark tradition of European and German Expressionist printmaking. You MUST restyle BOTH the subject AND the background — nothing may remain photographic. Reconstruct the entire image from hand-carved black ink marks on white paper: strong angular gouged lines, rough chiseled strokes, high-contrast solid black masses against bare white, dense parallel hatching for shadow, and the raw, slightly uneven texture of relief printing where the carving tool is visible. No grey gradients — only carved black and white. The result must look like a hand-printed woodcut. Output only the image." },
  { id: "graffiti", label: "グラフィティ風",
    prompt: "Completely transform this image into urban graffiti / street art spray-painted on a concrete wall. You MUST restyle BOTH the subject AND the background — nothing photographic may remain. Re-render the machine as a bold spray-paint mural: thick black outlines, vivid clashing fluorescent colors, drips and aerosol overspray, stencil-art elements, wildstyle lettering and tags, paint splatter, and a weathered concrete or brick wall background with cracks, torn posters and grime. Add spray texture, gradient fades and a rebellious street-art energy. The whole image must look like a real graffiti piece sprayed on a city wall. Output only the image." },
  { id: "artdeco", label: "アール・デコ風",
    prompt: "Completely redesign this image as a 1920s–30s Art Deco illustration / travel poster. You MUST restyle BOTH the subject AND the background — nothing may remain photographic. Rebuild the machine with sleek, streamlined geometric forms, bold symmetry, strong vertical lines and stylised elegance. Use a luxurious Art Deco palette of black, gold and metallics with rich jewel tones, flat poster-like areas of color, sunburst and zigzag motifs, stepped geometric ornament and elegant geometric borders. Add refined Deco geometric lettering if fitting. The result must read as a glamorous, symmetric, retro-futuristic Art Deco poster. Output only the image." },
  { id: "pointillism", label: "点描派風",
    prompt: "Completely repaint this image as a Pointillist / Divisionist painting in the manner of Georges Seurat and Paul Signac. You MUST repaint BOTH the subject AND the background — nothing may remain photographic. Render the ENTIRE image out of countless tiny distinct dots of pure, unmixed color placed side by side, letting the eye blend them optically into form and light. Use luminous complementary color contrasts and a bright, vibrating, sunlit atmosphere; every surface must be built from visible separate color points, not smooth paint. CONSTRAINTS: keep the original composition, pose and framing — only the technique becomes pointillist dots. Output only the image." },
  { id: "expressionism", label: "表現主義風",
    prompt: "Completely repaint this image as a German Expressionist painting in the anguished spirit of Edvard Munch and Die Brücke. You MUST repaint BOTH the subject AND the background — nothing may remain photographic. Distort and exaggerate the forms with nervous, jagged, swirling brushstrokes and warped perspective; use harsh, emotional, non-naturalistic color — acid greens, bruised purples, feverish reds and sickly yellows — clashing for psychological tension. The sky and background should writhe with turbulent painted energy. The image must feel raw, anxious and emotionally intense rather than realistic. Output only the image." },
  { id: "klimt", label: "クリムト風",
    prompt: "Completely repaint this image as a Symbolist 'Golden Phase' painting in the ornate style of Gustav Klimt. You MUST restyle BOTH the subject AND the background — nothing may remain photographic. Drench the image in shimmering gold leaf and bronze, and cover every surface with dense decorative pattern — spirals, eyes, triangles, rectangles, mosaic tessellation and intricate ornament. Combine flat, mosaic-like gilded areas with selectively detailed focal points, set against a glittering gold background. Use a jewel-toned, byzantine, luxuriously patterned palette. The machine should become a richly ornamented golden icon embedded in pattern. Output only the image." },
  { id: "mosaic", label: "ビザンティン・モザイク風",
    prompt: "Completely transform this image into a Byzantine gold-ground mosaic, like those in an ancient Orthodox cathedral. You MUST rebuild BOTH the subject AND the background — nothing may remain photographic. Reconstruct the ENTIRE image from thousands of small, irregular glass and stone tesserae (mosaic tiles) set with visible grout lines between them, catching light at slight angles. Render the machine as a solemn, frontal, iconic figure against a shimmering flat GOLD tessellated background, with a glowing halo, stylised flattened forms, and rich deep blues, reds, greens and gold tiles. The result must clearly read as an antique tile mosaic. Output only the image." },
  { id: "papercraft", label: "ペーパークラフト風",
    prompt: "Completely transform this image into a papercraft / low-poly paper-model scene — the machine built entirely out of folded and glued paper. You MUST restyle BOTH the subject AND the background — nothing may remain photographic. Reconstruct the machine as flat polygonal paper facets folded along visible crease lines, with slightly imperfect cut edges, small glue tabs, soft matte paper texture, and gentle real shadows cast between the folded planes as if photographed under soft studio light. Place it in a simple papercraft diorama where the background and ground are also made of colored construction paper / cardstock. The whole scene must look like a handmade paper model. Output only the image." },
  { id: "kirie", label: "切り絵風",
    prompt: "Completely transform this image into a layered kirie (切り絵) paper-cut artwork. You MUST restyle BOTH the subject AND the background — nothing may remain photographic. Re-render the entire scene as cleanly knife-cut silhouettes and shapes from several layers of colored paper, stacked with subtle drop shadows between layers to give gentle depth. Reduce the machine to bold, simplified flat cut-out shapes connected by delicate paper bridges, with crisp edges and no gradients — flat planes of color only. Keep the silhouette clean and instantly readable. The result must look like a handcrafted multi-layer paper-cut. Output only the image." },
  { id: "blueprint", label: "ブループリント風",
    prompt: "Completely transform this image into a technical blueprint / cyanotype engineering drawing of the machine. You MUST restyle BOTH the subject AND the background — nothing may remain photographic. Re-render everything as precise thin WHITE and pale-cyan technical line-work on a solid deep blueprint-blue background: clean orthographic-style outline drawing, construction lines, hidden dashed lines, dimension arrows and measurement callouts, a ruled grid and border, a title block in the corner, and handwritten-style technical annotations and part numbers. No photographic shading or color — only blueprint line-art. The result must look like a real engineering blueprint of the mobile suit. Output only the image." },
  { id: "pixelart", label: "ドット絵風",
    prompt: "Completely transform this image into retro 16-bit PIXEL ART (ドット絵), like a 1990s video-game sprite. You MUST restyle BOTH the subject AND the background — nothing may remain photographic. Rebuild the ENTIRE image from a low-resolution grid of clearly visible square pixels with a deliberately limited indexed color palette, hard-edged dithering for gradients and shading, crisp pixel outlines and chunky aliased edges — absolutely no smooth anti-aliasing or blur. Render the background as a simple tiled game scene. The whole image must look like an authentic pixel-art game sprite. Output only the image." },
  { id: "glitch", label: "グリッチアート風",
    prompt: "Completely transform this image into digital GLITCH ART / databending corruption. You MUST distort BOTH the subject AND the background — nothing may remain clean or photographic. Tear the image apart with digital artifacts: horizontal datamosh displacement, RGB chromatic-aberration channel splitting into red/green/blue ghosts, blocky JPEG compression smears, pixel-sorting streaks, scanline tearing, signal noise, corrupted color bands and broken-screen distortion. Fragment and shift slices of the machine sideways as if the video signal is malfunctioning. The result must look like a corrupted, broken digital image. You MAY aggressively displace and duplicate parts. Output only the image." },
];
export function initStyleOpts(s) {
  const o = {};
  (s.fields || []).forEach((f) => { o[f.key] = f.type === "select" ? ((f.options[0] && f.options[0].value) || "") : ""; });
  return o;
}
export const AI_MODELS = [
  { group: "Google · Gemini(Nano Banana)", items: [
    { id: "gemini-3-pro-image", label: "Nano Banana Pro(最高品質)" },
    { id: "gemini-3.1-flash-image", label: "Nano Banana 2(高速)" },
    { id: "gemini-2.5-flash-image", label: "Nano Banana(従来)" },
  ] },
  { group: "OpenAI · GPT Image", items: [
    { id: "gpt-image-2", label: "GPT Image 2(最新)" },
    { id: "gpt-image-1.5", label: "GPT Image 1.5" },
    { id: "gpt-image-1-mini", label: "GPT Image 1 mini(軽量)" },
  ] },
];
export const isOpenAImodel = (m) => /^gpt-image/.test(m || "");
export const aiProviderLabel = (m) => (isOpenAImodel(m) ? "OpenAI" : "Google Gemini");
/* 選択モデルに対応する端末ローカルのAPIキーを返す */
export const aiActiveKey = (ai) => (ai ? (isOpenAImodel(ai.model) ? ai.openaiKey || "" : ai.geminiKey || "") : "");
export const AI_MODEL_OPTS = AI_MODELS.flatMap((g) => g.items.map((it) => ({ value: it.id, label: it.label, note: isOpenAImodel(it.id) ? "OpenAI" : "Gemini" })));
